[project]
name = "turtle-nav"
version = "0.1.0"
description = "UPM Programming Aerial Robotics Assignment I"
authors = ["Alvaro <alvgaona@gmail.com>"]
channels = ["conda-forge", "robostack-staging"]
platforms = ["linux-64"]

[tasks]
build = { cmd = [
  "colcon",
  "build",
  "--symlink-install",
  "--event-handler",
  "console_direct+",
  "--cmake-args",
  "-G Ninja",
  "-DPython3_EXECUTABLE=$CONDA_PREFIX/bin/python",
] }
test = { cmd = [
  "colcon",
  "test",
  "--ctest-args",
  "tests",
  "turtle-nav",
  "&&",
  "./build/turtle_nav/turtle_nav_test",
], depends-on = [
  "build",
] }

[dependencies]
clang-format = ">=18.1.3,<18.2"
cmake = ">=3.28.3,<3.29"
colcon-common-extensions = ">=0.3.0,<0.4"
compilers = ">=1.7.0,<1.8"
ninja = ">=1.12.0,<1.13"
pkg-config = ">=0.29.2,<0.30"
ros-humble-ament-cmake-auto = ">=1.3.7,<1.4"
ros-humble-desktop = ">=0.10.0,<0.11"
ros-humble-turtlesim = ">=1.4.2,<1.5"
spdlog = ">=1.12.0,<1.13"
casadi = ">=3.6.7,<4"
librerun-sdk = ">=0.20.1,<0.21"
libtinyspline = ">=0.6.0,<0.7"

[activation]
scripts = ["install/setup.sh"]
